// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf-0Q1cfGjjVO54XlFOGTkeoqsnojjG9M',
    appId: '1:670990709976:web:78226daf561e2292a253ad',
    messagingSenderId: '670990709976',
    projectId: 'music-app-ae74e',
    authDomain: 'music-app-ae74e.firebaseapp.com',
    storageBucket: 'music-app-ae74e.firebasestorage.app',
    measurementId: 'G-TZR2XMRNNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCILarJjXDZaFUlZILgFxRrBc9_ZHJqbpQ',
    appId: '1:670990709976:android:2aac67d96c7f518ca253ad',
    messagingSenderId: '670990709976',
    projectId: 'music-app-ae74e',
    storageBucket: 'music-app-ae74e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXCjg_d3CXkIsGaXl5Jvje-mQyEEXRmL4',
    appId: '1:670990709976:ios:94ae959a2530bc78a253ad',
    messagingSenderId: '670990709976',
    projectId: 'music-app-ae74e',
    storageBucket: 'music-app-ae74e.firebasestorage.app',
    iosBundleId: 'com.example.westifyMusikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXCjg_d3CXkIsGaXl5Jvje-mQyEEXRmL4',
    appId: '1:670990709976:ios:94ae959a2530bc78a253ad',
    messagingSenderId: '670990709976',
    projectId: 'music-app-ae74e',
    storageBucket: 'music-app-ae74e.firebasestorage.app',
    iosBundleId: 'com.example.westifyMusikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf-0Q1cfGjjVO54XlFOGTkeoqsnojjG9M',
    appId: '1:670990709976:web:441430e2ac088fc6a253ad',
    messagingSenderId: '670990709976',
    projectId: 'music-app-ae74e',
    authDomain: 'music-app-ae74e.firebaseapp.com',
    storageBucket: 'music-app-ae74e.firebasestorage.app',
    measurementId: 'G-C9RXHD4JP0',
  );

}